### PR TITLE
Styling for other message states

### PR DESCRIPTION
**Pull request by wedaly**
This PR adds styling and copy for all currently supported message states:

* Skipped verification: 
image

* Submitted verification:
image

* Verification approved:
image

* Verification denied:
image

* Verification error:
image

@srpearce Please review the message strings.  (I pulled them directly from the UI designs)
@frrrances Please review the styling (especially the color values).

**Note**: This PR contains the changes from https://github.com/edx/edx-reverification-block/pull/22.  The changes specific to this PR are in the second commit.

### CODE REVIEW

**Comment by rlucioni** [comment]
Is the minified reverification CSS supposed to be tracked in this repo? Otherwise, :+1:.

**Comment by clintonb** [comment]
:+1:

**Comment by wedaly** [comment]
@rlucioni Yes, unfortunately XBlock doesn't provide any other mechanism for asset pipelining :(

**Comment by srpearce** [comment]
@wedaly I've added text revisions for the above messages, as well as the other existing messages, in the "LMS Component" section of the [In-course re-verification UX page](https://openedx.atlassian.net/wiki/display/UX/In-course+re-verification+UX). Since this PR has been merged, is there somewhere else I should add these revisions?

**Comment by wedaly** [comment]
@srpearce Nope, I'll make those changes now in a separate PR and tag you for review.  Thanks!

**Pull request merged**
