### PR TITLE
Update messaging

### PR DESCRIPTION
**Pull request by wedaly**
* Messaging updates based on doc review
* Increase contrast on links for a11y.

@srpearce please review the doc changes.

# Screenshots

* Need to verify:
image

* Skip confirmation:
image

* Skipped:
image

* Submitted:
image

* Approved:
image

* Denied:
image

* Error:
image

### CODE REVIEW

**Comment by wedaly** [comment]
@srpearce @frrrances I'm a little concerned about that last state.  We currently don't give them a way back into the flow -- should it look more like the denied state?

**Comment by srpearce** [comment]
@wedaly I think giving users a way back into the flow would be great - I'm just not sure why errors would occur and I don't know where the user can go from here technically. Since we tell users to try to verify their identity again (something that I just added without knowing exactly how they would do that), can we include a "try again" button?

Also, can you give me some more context for the "denied" message? Are there specific reasons for the denial that we could tell users about?

**Comment by srpearce** [comment]
Oh, and the text for the "denied" message above is incorrect. It should be this:

To receive credit in this course, you must try to verify your identity again. If you do not want to verify your identity, you can <link>opt out of verification</link>. However, you will no longer be eligible for credit in the course.

**Comment by wedaly** [comment]
@srpearce 

1. The main error state is when we can't contact Software Secure.  There are a variety of reasons why this might happen, but it's possible that a second attempt could be successful even if the first failed.

2. Yes, we could include a "Try Again" button.

3. Users are denied if the photos they submit don't match the ID photos they submitted at the start of the course.

I'll update the PR to fix the "denied" message.

**Comment by wedaly** [comment]
@srpearce updated:

* Denied:
image

* Error
image

**Comment by srpearce** [comment]
@wedaly LGTM :+1:

**Pull request merged**
